### ISSUE TITLE
PHX Ground Radar Tag assigned Runway

### ISSUE THREAD

**Issue by Calaelen** [VATGER-Nav/edww-package#102]
Assign Runway im Ground Radar Tag hilft Lotsen in EDDV auf den ersten Blick den richtigen Pushback zu geben.
In Hamburg wird es auch als Failsafe genutzt. 

Sofern das möglich ist und eine generelle Anzeige nicht erwünscht ist:  nur in EDDV einblenden

![image](https://github.com/VATGER-Nav/edww-package/assets/524760/fff7f3ec-31c2-4450-8385-e4d8ca1eec44)

**Comment by hannesaltmann** [comment]
Wurde mit v0.9.9 füt EDDV bereits umgesetzt.
