### ISSUE TITLE
Icon for unconcerned aircraft

### ISSUE THREAD

**Issue by RagingLightning** [VATGER-Nav/edww-package#107]
I feel like the scale of unconcerned aircraft is maybe a little off... They are bigger than concerned ones...

![grafik](https://github.com/VATGER-Nav/edww-package/assets/29428184/1ffaade7-4afe-4e66-a752-4fadd244bd06)

Personally, I think even a single dot would suffice. Unfortunately, I was not able to track down an image of the original Phoenix sowtware to compare to, so it may be that this is totally accurate to the original.

Edit: I can't set the label, so I'll clarify that this is the Phoenix Night Tower profile

**Comment by hannesaltmann** [comment]
Settings x-checked and according to real-world Phoenix system. Thanks for the reports though!
