### ISSUE TITLE
Wunstorf (ETNW) Centerline und Sector boundry fehlen im TWR Profil

### ISSUE THREAD

**Issue by Balu1412** [VATGER-Nav/edww-package#108]
Für ETNW fehlen alle Centerlines, es wäre schön wenn man sich diese bei bedarf einblenden könnte oder sie automatisch erscheinen wenn man sich als ETNW_TWR einloggt.

Des weiteren wäre es vielleicht noch praktisch sich die Sektor grenzen innerhalb der Hannover CTR einblenden zu können (siehe GEMIL FLIP VAD Charts für ETNW, dort ist sie als strich punkt Linie eingezeichnet).

MfG
Lars :-)

**Comment by hannesaltmann** [comment]
Centerlines werden mit dem nächsten Update Logon basiert für ETNW hinzugefügt. 

> Des weiteren wäre es vielleicht noch praktisch sich die Sektor grenzen innerhalb der Hannover CTR einblenden zu können (siehe GEMIL FLIP VAD Charts für ETNW, dort ist sie als strich punkt Linie eingezeichnet).

Das zu gibt es aktuell noch keinen genauen SOPs, deshalb wird das auch noch nicht hinzugefügt. Kümmere mich aber darum!
