### ISSUE TITLE
Shortcuts in Radar package

### ISSUE THREAD

**Issue by Calaelen** [VATGER-Nav/edww-package#111]
Bisher hatten wir auch die beiden folgenden Shortcuts. Könnten die bitte weiterhin im Pack bleiben?

Radar Profile:
ALT+D = Tactical Directs
ALT+U = show Upper Splits

**Comment by hannesaltmann** [comment]
ALT+D gibt es, man muss aber eingeloggt sein (Maps ist abhängig von Station)

ALT+U wäre ein Doppelbelegung mit der Quick Look Funktion von Topsky und ist somit nicht möglich. Diese Map haben wir auch gar nicht.

**Comment by Calaelen** [comment]
Normal View
![image](https://github.com/VATGER-Nav/edww-package/assets/524760/5728cf95-43af-4502-a145-3bb88fcfa523)

Alt-U
![image](https://github.com/VATGER-Nav/edww-package/assets/524760/e96cd473-7943-438e-914f-3ec6b0fb67a5)

Quicklook kenne ich nicht als Alt-U. Vielleicht dann eine alternative Tastenkombie?
