### ISSUE TITLE
EDYY Tag

### ISSUE THREAD

**Issue by hannesaltmann** [VATGER-Nav/edww-package#118]
- Add Scratchpad
- Check SI indicator visibility when manually changing the next sector

**Comment by ManuelPick** [comment]
- Missing assign squawk option

**Comment by lucianoasmus** [comment]
Delete DFS-Squawk filter item ("V", "PJE", "FIS" etc.)

**Comment by lucianoasmus** [comment]
I would prefer the ASP menu at a different place that it is right now. Out of a perspective of being used to the Bremen Pack, I constantly hit it while intending to open the waypoint menu, out of the Langen EDYY Pack I try to open the ASP menu by clicking the GS and neither works on intuition😄

**Comment by lucianoasmus** [comment]
As seen in the picture in #126 the MTCD Dot is displayed left of the callsign. Maybe that is possible without moving the whole first row?

**Comment by hannesaltmann** [comment]
fixed
