### ISSUE TITLE
EDYY Direct Map

### ISSUE THREAD

**Issue by ManuelPick** [VATGER-Nav/edww-package#119]
Possibly add point BERXO to easier identify what is east of said point.
![grafik](https://github.com/VATGER-Nav/edww-package/assets/40025269/938f3887-47af-46e6-be2a-e74f3d0c814e)

**Comment by hannesaltmann** [comment]
> Add Points NOGRO, GALSO, ABNET

Alreadyy covered by this:

![image](https://github.com/VATGER-Nav/edww-package/assets/71515220/7ae8c122-e39f-4973-97a1-3266474e7926)

**Comment by lucianoasmus** [comment]
Move some points up/down/left/right of the fix to enhance readability out of a zoomed-out view with smaller monitors

**Comment by hannesaltmann** [comment]
> Possibly add point BERXO to easier identify what is east of said point.
Fixed

> Move some points up/down/left/right of the fix to enhance readability out of a zoomed-out view with smaller monitors

The current setting is good for most monitors (as it has been for all direct maps in the last two years). Can't support any setup in every situation.
