### ISSUE TITLE
ASR Shortcuts 

### ISSUE THREAD

**Issue by hannesaltmann** [VATGER-Nav/edww-package#12]
EDDB auf 2
EDDH auf 3
EDDV auf 4
EDDW auf 5
EDXW auf 6
EDHL auf 7
EDAH auf 8
ETNL auf 9

EDVK, EDVE und EDHI haben nichts. Muss etwas hier geändert werden?

**Comment by lucianoasmus** [comment]
Vorschlag, EDHL und EDHI ins EDDH ASR mit rein und keinen Shortcut extra dafür. Wenn Verkehr da ist, dann meist eh mit S1-Tower online, ansonsten kann man ja .center [ICAO] (F1+c) oder kurz rüberdraggen.

**Comment by hannesaltmann** [comment]
Könnte jedoch Probleme mit GRP geben
