### ISSUE TITLE
[EDYY] Larger CFL menu

### ISSUE THREAD

**Issue by lucianoasmus** [VATGER-Nav/edww-package#123]
With a new topsky version, the cfl menu can be extended in the "setup->cfl->extended" to show a larger menu. Also, a wider menu (like the old one) would fit better aswell (if that is still available):
<img width="823" alt="image" src="https://github.com/VATGER-Nav/edww-package/assets/62181068/06b2d153-7979-460a-9832-fd1b3061f9aa">
München has the extended cfl setup somehow enabled as standard, maybe that is possible here aswell.

**Comment by hannesaltmann** [comment]
Wider menu is not possible.
