### ISSUE TITLE
[EDYY] Change Target symbol

### ISSUE THREAD

**Issue by lucianoasmus** [VATGER-Nav/edww-package#126]
Das target ist noch ein ausgefülltes quadrat, das reale ist standardmäßig unausgefüllt mit einem Punkt in der mitte. 
![C5ajA8uWcAAic0T](https://github.com/VATGER-Nav/edww-package/assets/62181068/4a511a39-42ad-47e5-ba96-baccc015bab6)

(Manchmal auch ein Dreieck oder Kreis, aber weniger relevant für uns da vermutlich nicht umsetzbar)

**Comment by hannesaltmann** [comment]
fixed 

Den Punkt wirst du aber nicht bemerken, da die Linie vom Label bei Euroscope immer mittig vom target aus geht
