### ISSUE TITLE
ED-R Nummern an der Area

### ISSUE THREAD

**Issue by Deinemold** [VATGER-Nav/edww-package#129]
Im Radarscreen werden keine Nummern an den ED-Rs angezeigt. Besonders die VFRler fragen nach der Nummer und nicht nach dem Namen. Eine Zuordnung der Namen zu den Nummern ist sehr wahrscheinlich, für die meisten unter uns nicht möglich. Es wäre cool, wenn wir die Nummern irgendwie mit zum Namen bekommen würden.

VG Simon 
![EDR](https://github.com/VATGER-Nav/edww-package/assets/74827197/a5b8c2bc-4203-46d3-8a3a-3e253c514a83)

**Comment by hannesaltmann** [comment]
Super Idee, danke
