### ISSUE TITLE
RRS bei DEP Runway fehlt

### ISSUE THREAD

**Issue by Deinemold** [VATGER-Nav/edww-package#133]
Die RRS-Marker werden nur bei der Arr-Runway angezeigt und nicht bei der Dep-Runway. Betrifft sowohl das TWR als auch das Bremen Profil.

VG Simon

**Comment by hannesaltmann** [comment]
Wird mit der nächsten Version sowohl bei DEP rwy als auch ARR rwy angezeigt.
