### ISSUE TITLE
Topsky QDM buggy

### ISSUE THREAD

**Issue by ascarion** [VATGER-Nav/edww-package#143]
With the beta pack, I frequently have issues with the Topsky QDM tool, which refuses to draw from fixes and will only work between radar targets. Even then it is slow to apply and will frequently not stick to aircraft when clicking on the label instead of the radar target.
I did not experience this behaviour in the old RG Berlin package, or other FIR packages. I understand fixing this might not be easy if at all possible.
I am using Euroscope Version 3.2.3

**Comment by hannesaltmann** [comment]
Will check, but I will suspect it to be some sort of a Topsky bug.

**Comment by hannesaltmann** [comment]
Missing dummy items might cause the issue. Will investigate further with Version 0.9.15
