### ISSUE TITLE
Add EBG North/South Sectors to Radar-Menu Views

### ISSUE THREAD

**Issue by BremenIdentified** [VATGER-Nav/edww-package#175]
currently EGB BER and EBG Ost only
![image](https://github.com/VATGER-Nav/edww-package/assets/158813995/17d62669-6b18-4d46-b0f5-0907a4bebcbf)

Add EGB North and South
![image](https://github.com/VATGER-Nav/edww-package/assets/158813995/564ddb3d-ae05-4da5-975a-adf7910df361)

**Comment by hannesaltmann** [comment]
Will be added next release (v0.9.149
