### ISSUE TITLE
SRR-Filter not working

### ISSUE THREAD

**Issue by BremenIdentified** [VATGER-Nav/edww-package#176]
SRR-Filtering ist not working correctly. TAG is the same without filtering.
Tested with SQ7000
![image](https://github.com/VATGER-Nav/edww-package/assets/158813995/df5097f7-f593-48d7-8068-03fa40e7aabd)
![image](https://github.com/VATGER-Nav/edww-package/assets/158813995/a93366c3-2be6-4357-84ca-96928117e0f8)

**Comment by hannesaltmann** [comment]
Bug confirmed. 

The following entry is missing in the Topsky Settings
System_FIC_Position_Free_Filtered=1

Will be fixed soon!
