### ISSUE TITLE
SI toggle not working

### ISSUE THREAD

**Issue by BremenIdentified** [VATGER-Nav/edww-package#177]
shortly before crossing sector border / switching to tower the SI toggle wont work in EDWW-profile. remains on freq. left click opens menu but right click wont work. Dont know if its a bug or a feature ;)
![image](https://github.com/VATGER-Nav/edww-package/assets/158813995/766501d2-2450-417e-898a-1a62b5607318)
![image](https://github.com/VATGER-Nav/edww-package/assets/158813995/5c519fb3-40ab-4e76-a479-835acd3ffad8)

**Comment by hannesaltmann** [comment]
Unfortunately limitation of Topsky. Not much I can do here :/
