### ISSUE TITLE
Routedraw bei DEP-List 

### ISSUE THREAD

**Issue by Deinemold** [VATGER-Nav/edww-package#186]
Im alten Bremen Pack konnte man per links oder rechts Klick auf die Destination in der DEP-Liste ein Routedraw anzeigen. Wäre cool, wenn man das wieder hinzufügen könnte.

**Comment by hannesaltmann** [comment]
Ist der Report für das EDWW (APP/CTR) oder Tower Profile? Beim Tower Profile wird keine Umsetzung erfolgen, da hier VATGER einheitliche Settings verwendet werden.

**Comment by Deinemold** [comment]
Der Report war eigentlich für beide Packs. Wenns bei TWR nicht geht, dann wäre es bei EDWW schön. An wen muss denn das Feedback zu den standardisierten Listen? VG Simon

**Comment by hannesaltmann** [comment]
Alles klar, dann EDWW. 

Für TWR kannst du dich bei der ATD Leitung melden.

**Comment by hannesaltmann** [comment]
@Deinemold gerade nochmal zeit gehabt das zu checken. Mit einem Rechtsklick auf das Callsign wird das Route Draw aktiviert. Clickspot ist vorhanden, nur bei einem anderen Feld. Ich würde hier also nichts ändern, außer ATD würde etwas anderes wollen.
