### ISSUE TITLE
Colour choices in ground layout make reading aircraft tags more difficult

### ISSUE THREAD

**Issue by ascarion** [VATGER-Nav/edww-package#204]
I adore the new EDDB ground layout, thank you for that. The level of detail and zoom-level appropriate display of labels is very well thought out.

Unfortunately, the colour choice in some areas makes it a rather noisy backdrop to what should be the primary information on the radar display: The aircraft.
Reducing the contrast with some lines would go a long way towards improving that. Obviously, this is to some degree personal preference. Maybe it could be made optional, similar to line and background colours for the Bremen Radar profile.

Here's what I would suggest to change for the dark version:
1. Reduce taxiway colour brightness
2. Reduce stand line and label colour brightness
3. Potentially reduce the brightness of taxiway labels

For the PHX Day profile:
1. Make aircraft silhouette a little darker
2. Change taxiway or arrival aircraft colour as they are currently identical.
3. Increase the brightness of stand and taxiway labels
4. Increase the brightness of stand lines

For comparison, old vs new:
![firefox_0bJnGqZA2u](https://github.com/VATGER-Nav/edww-package/assets/237600/147645d5-f1e5-4110-90ce-0cead8f33a47)

**Comment by hannesaltmann** [comment]
@ManuelPick

**Comment by hannesaltmann** [comment]
@ascarion After some time try out various settings, it will most likely change to these colours:

![image](https://github.com/VATGER-Nav/edww-package/assets/71515220/26b83aad-368c-4987-851b-a59cba07614b)

![image](https://github.com/VATGER-Nav/edww-package/assets/71515220/a5c643da-4822-434d-a56d-5da83cc5c51d)
