### ISSUE TITLE
Kontrast der Ground Radar Leiste + CPDLC-Settings

### ISSUE THREAD

**Issue by GeheimagentNr1** [VATGER-Nav/edww-package#205]
Die Hinweisfarbe für die Veränderung des QNH, dass LVP aktiv ist oder die verschiedenen Funktionen wie RIM etc. deaktiviert sind, sogt dafür, dass die Schrift nicht mehr gut lesbar ist.
![image](https://github.com/VATGER-Nav/edww-package/assets/20889593/cfd65f43-c705-4f61-b788-90ee54008732)

Gleiches gilt außerdem für den CPDLC-Settings "Connect"/Status Button, dass "Online" ist auch dort kaum lesbar.
![image](https://github.com/VATGER-Nav/edww-package/assets/20889593/999afb45-222c-4dfd-a913-e4ca965febdf)

Obendrein ist das Weiß, was in der Schrift von Ground Radar Leiste bzw. Departure List vor allem bei dunklem Zimmer, aber auch bei hellem sehr grell und anstrengend für die Augen.

Getestet im "EDWW FIR - TWR PHX NIGHT" Packet.

**Comment by hannesaltmann** [comment]
Wird nicht angepasst werden. Die Farbeinstellungen betreffen auch gleichzeitig Farben in Tags und Listen. Diese sollen so schon gern bleiben. Entsprechend eine Limitation vom GroundRadar Plugin und vom Topsky Plugin. Ich denke aber nicht, dass es zu stark problematisch ist :)
