### ISSUE TITLE
CPDLC always rejecting at EDDW

### ISSUE THREAD

**Issue by NikolasHB** [VATGER-Nav/edww-package#208]
Bin nicht sicher, ob es sich hierbei tatsächlich um einen Bug im Pack handelt, oder etwas an meiner Konfiguration falsch ist (ich wüsste aber nicht, was das sein könnte). Wenn kein Bug gerne schließen.

Ausnahmslos jeder CPDLC Predep Clearance request wird sofort und automatisch abgelehnt, Beispiel:
> 1546 DLH9876 REQUEST PREDEP CLEARANCE DLH9876 A20N TO EDDB AT EDDW STAND 3 ATIS E
> 1546 DLH9876 RCD REJECTED REVERT TO VOICE PROCEDURES

Dies tritt immer auf. Der Clearance Request ist jeweils korrekt. Die neueste Pack-Version ist installiert. 

Ich habe mir mal die TopSkyCPDLC.txt im Vergleich zwischen FIR-Beta-Pack und altem RG Bremen Pack angeschaut:
FIR-Beta: DCL:EDDB,EDDH,EDDV:...
RG Bremen: DCL:EDDH,EDDV,EDDW,EDXW,EDHL,EDHI,EDVE,EDVK:...
Eventuell liegt es daran?

**Comment by hannesaltmann** [comment]
In EDDW gibt es kein DCL/PDC. Das ist ein Fehler im RG Bremen Pack

**Comment by NikolasHB** [comment]
Laut SOP schon: "PDC: The use of PDC (Pre Departure Clearance) is permitted in Bremen, but not mandatory. The logon code "EDDW" shall be used."

Ist das dann ein Fehler in den SOP?

**Comment by hannesaltmann** [comment]
Die SOP ist falsch und wurde jetzt angepasst.
