### ISSUE TITLE
VFR Label sind unübersichtlicher

### ISSUE THREAD

**Issue by GeheimagentNr1** [VATGER-Nav/edww-package#209]
Durch die neue Anordnung rechts unten ist die Zuordnung der VFR Labels schwieriger:
![image](https://github.com/VATGER-Nav/edww-package/assets/20889593/4c14fcf5-6b86-45ef-9b7e-b2c389397db4)

Mit der alten Variante, direkt über dem VFR Punkt, ist das deutlich einfacher:
![image](https://github.com/VATGER-Nav/edww-package/assets/20889593/60804d51-ecb3-4d48-82ea-aee0cbae6c56)

Vor allem im Bereich Hannover ist die Zuordnung der VFR Label schwierig:
![image](https://github.com/VATGER-Nav/edww-package/assets/20889593/b4389d9f-2ddc-49ab-b0b4-040676ec1c71)

**Comment by hannesaltmann** [comment]
In der neuen Version werden die Labels sich immer direkt unter dem Fix befinden.
