### ISSUE TITLE
PHX Tower, Aircraft Tag Änderungswünsche

### ISSUE THREAD

**Issue by GeheimagentNr1** [VATGER-Nav/edww-package#212]
In der Radaransicht ist der Remark nicht vollständig zu sehen, vor allem bei VFR Fliegern könnten die Tags länger sein, weil so viele Infos zum Flieger notiert werden, wie Sprache, Absichten (Traffic Circuts, Einflug, Ausflug, Landung), QNH.  
Es wäre daher praktisch den gesamten Remark anzugezeigen zumindest, wenn das Tag gehovert wird.

![](https://github.com/VATGER-Nav/edww-package/assets/20889593/92777579-6a27-4bb7-b4f7-90623f6b4101)

Im alten Pack wurde im Ground Tag, der Ground Speed und die Runway angezeigt.  
Der Ground Speed war immer nützlich, um einzuschätzen, ob der Flieger weiter rollt oder ob er gleich stehen bleibt. Im RL hat man für sowas eine Tower View, das habe ich meistens nicht. Ich habe nur die Ground View.  
Die Runway war immer nützlich, um abweichende Runways zu erkennen, z.B. in EDDH wenn ein VFR Flieger abweichend von der 23 oder im EDXW von 06/24 abheben soll. Hilft einfach sehr für die Situation Awareness, wenn es im Tag steht.

![](https://github.com/VATGER-Nav/edww-package/assets/20889593/79df6621-f8a8-4308-ad78-fb4e10e06190)

**Comment by hannesaltmann** [comment]
> In der Radaransicht ist der Remark nicht vollständig zu sehen, vor allem bei VFR Fliegern könnten die Tags länger sein, weil so viele Infos zum Flieger notiert werden, wie Sprache, Absichten (Traffic Circuts, Einflug, Ausflug, Landung), QNH.
> Es wäre daher praktisch den gesamten Remark anzugezeigen zumindest, wenn das Tag gehovert wird.

Diese Settings sind VATGERweit gleich und eine Abweichung ist hier nicht vorgesehen. Solltest du hier Änderungswünsche haben, meldest du dich bitte direkt bei der ATD Leitung von Vatsim Germany. 



> Im alten Pack wurde im Ground Tag, der Ground Speed und die Runway angezeigt.
> Der Ground Speed war immer nützlich, um einzuschätzen, ob der Flieger weiter rollt oder ob er gleich stehen bleibt. Im RL hat man für sowas eine Tower View, das habe ich meistens nicht. Ich habe nur die Ground View.
> Die Runway war immer nützlich, um abweichende Runways zu erkennen, z.B. in EDDH wenn ein VFR Flieger abweichend von der 23 oder im EDXW von 06/24 abheben soll. Hilft einfach sehr für die Situation Awareness, wenn es im Tag steht.

Das Groundlabel ist bewusst so gewählt, um die Darstellung möglichst einfach und aufgeräumt zu halten, was besonders bei größeren Airports wichtig ist. Aus diesem Grund wird auch keine GS im Groundlabel angezeigt werden. Die würdest du eh im Flugstreifen sehen können.
