### ISSUE TITLE
Gleicher Shortcut für 2 unterschiedliche Funktionen

### ISSUE THREAD

**Issue by GeheimagentNr1** [VATGER-Nav/edww-package#214]
Beim Lesen der Knowledgebase ist aufgelassen, dass der Shortcut "ALT + F" im Bremen Radar Profil für 2 Funktionen vergeben ist.  
Ist das Absicht, dass die Standardfunktion im Bremen Radar Profil überschrieben wird.

![](https://github.com/VATGER-Nav/edww-package/assets/20889593/699f6c01-ef62-4ae7-a10a-a9d7eb1c602b)

**Comment by hannesaltmann** [comment]
ALT + F ist im EDWW Profile für die FIS Sektoren hinterlegt. Für EDYY und EDUU bspw. für den F-Plan.
