### ISSUE TITLE
Add neighbouring groundlayouts to Main-ASRs

### ISSUE THREAD

**Issue by lucianoasmus** [VATGER-Nav/edww-package#216]
(EDWW Profile)
Hi,
Könnte man wieder das **EDHI** Groundlayout zum **EDDH ASR** sowie das **ETNW** Groundlayout zum **EDDV ASR** hinzufügen? Ich weiß, dass es mit den GRP Settings nicht ganz optimal ist, aber für TopDown reicht es allemal aus und so kann man einfach mal kurz rüber-pannen wenn man da ein Flieger stehen hat und muss sich nicht durch die Dateiordner wühlen. Hat jedenfalls mit den alten hervorragend funktioniert. Danke! <3

**Comment by hannesaltmann** [comment]
Moin, 

nach internen Beratungen haben wir uns entschieden dies nicht umzusetzen. Wir sind der Überzeugung, dass der Aufwand der Umstellungen und unterschiedlichen Layouts nicht im Einkang dem tatsächlichen Nutzen steht. Ein ASR aufzurufen ist eine Sache von wenigen Sekunden und kann auch bereits für solche Sessions vor einer Session erfolgen. 
Davon abgesehen ist eine Umsetzung durchaus schwieriger als in ehemaligen Setups, da fast alle Groundlayouts mittlerweile über das GR Plugin gezeichnet werden. 

Wir empfehlen eine individuelle Anpassung deines Setups mithilfe der Groundflayouts aus dem Sectorfile, welche immernoch recht aktuell sein sollten. Dass dann deine beiden ASR nicht überschrieben werden sollen, sollte denke ich klar sein. 

Grüße
