### ISSUE TITLE
EIDW hat keine TopSky Fixes der Approach runways

### ISSUE THREAD

**Issue by Calaelen** [VATGER-Nav/edww-package#222]
Man muss bei TopDown Approach alle fixes per Map manuell einblenden, wenn man EDWW_W_CTR lotst.

**Comment by hannesaltmann** [comment]
Hmm das hatte ich eigentlich mal gefixt, aber offensitlich wurde das mit einem anderen pull-request überschrieben. Ich schaue mich das nochmal an, danke

**Comment by hannesaltmann** [comment]
Mit dem nächsten Update fixed
