### ISSUE TITLE
Stand-Linien schlecht zu sehen

### ISSUE THREAD

**Issue by GeheimagentNr1** [VATGER-Nav/edww-package#224]
Problem betrifft: EDDH, EDDV, EDXW, EDHL, ob weitere betroffen sind, wurde nicht untersucht.  
  
Die Linien vom Taxiway zum Stand sind mit dem Update vom 04.05.24 in den oben genannten Airports schlecht zu sehen.  
  
Version vom 23.04.24

![](https://github.com/VATGER-Nav/edww-package/assets/20889593/1b83b200-6207-4fc2-b5a7-6c2799d47928)

Version vom 04.05.24

![](https://github.com/VATGER-Nav/edww-package/assets/20889593/c6531b23-9be5-47b7-b1ae-ab27881a2105)

**Comment by hannesaltmann** [comment]
Alternative Farbe für EDDH, EDDV, EDHL und EDXW erstellen (10 heller für Dark und 10 dunkler für Bright)

**Comment by hannesaltmann** [comment]
Fehler behoben, danke :)
