### ISSUE TITLE
Miles to go

### ISSUE THREAD

**Issue by BremenIdentified** [VATGER-Nav/edww-package#225]
Im aktuellen Pack scheint etwas mit den miles to go nicht zu stimmen.
![Screenshot 2024-05-04 205404](https://github.com/VATGER-Nav/edww-package/assets/158813995/95cdf431-a553-424a-9839-26c625c3c05b)

**Comment by hannesaltmann** [comment]
Topsky Bug, habe ich weitergeleitet

**Comment by hannesaltmann** [comment]
Es wird vorerst auf die v2.57 zurück gewechselt
