### ISSUE TITLE
Connectet as BOR EDAZ not active

### ISSUE THREAD

**Issue by janus45** [VATGER-Nav/edww-package#25]
I conncectet myself as BOR and there was no ARR under me all airports were set as Active except EDAZ.
<img width="240" alt="image" src="https://github.com/VATGER-Nav/edww-package/assets/50266363/a7b902f5-cd30-4c12-af23-ec557a3e5fc0">

**Comment by hannesaltmann** [comment]
Confirmed as wrong report
