### ISSUE TITLE
[All Profiles] Add + for Newbie Remark

### ISSUE THREAD

**Issue by lucianoasmus** [VATGER-Nav/edww-package#280]
Add TopSky Feature to display a "+" symbol above the tag if remark shows "NEWBIE", "BEGINNER" or "FIRST [Flight]" in various, correct and incorrect spellings (e. g. include "NEWBY" as well). Therefore controllers act more precautious, understanding and patient when seeing the mark. 
Additionally, "blind" or other disabilities which still let operate aircrafts on the network could be included.
As left click function, I suggest "open flight plan", but the Euroscope version, as the TopSky flight plan does not show any remarks. Inspiration in all, but this last point, can be taken from the Langen and München Packs as they have this feature already included.

**Comment by hannesaltmann** [comment]
Already for EDYY and EDUU profiles. Will be added for EDWW only next AIRAC.
