### ISSUE TITLE
[EDWW] Add toggleable "Freq"-Indicator on Bremen Profile

### ISSUE THREAD

**Issue by lucianoasmus** [VATGER-Nav/edww-package#281]
Included in all german iCAS Packs (including Bremen FIR EDUU-profile), so I would love to see it in our EDWW profile as well :)
Can be used for various purposes and serves generally as an additional highlight function. 
![image](https://github.com/VATGER-Nav/edww-package/assets/62181068/e4321a61-8248-4ec1-948a-b50b43cfdd8e)

**Comment by hannesaltmann** [comment]
needs to be added as Tag Item

Mark Item can also be added
