### ISSUE TITLE
ETMN_APP Automatic Sector activation

### ISSUE THREAD

**Issue by Balu1412** [VATGER-Nav/edww-package#282]
Logged man sich als ETMN_APP ein ohne das ETNT_APP online ist wird die ETNT AOR nicht automatisch aktiviert sowie ETNT als activ Airport gesetzt.
Nach der SOP soll ETMN ETNT mit machen falls nicht online

Des weiteren wäre ein Transceiver von AfV für ETMN_APP bei ETNT praktisch

**Comment by hannesaltmann** [comment]
Die SOP ist falsch. ETNT covert ETMN und nicht andersrum.
