### ISSUE TITLE
Missing Info/Radio Frequencies

### ISSUE THREAD

**Issue by pa-ulex** [VATGER-Nav/edww-package#305]
- [x] Leck Radio (EDXK) | 132.565 
- [x] Flensburg Radio (EDXF) | 122.855
- [x] Pellworm Radio (EDHP) | 123.910
- [x] Husum Radio (EDXJ) | 125.835
- [x] Kropp Radio (EDXC) | 118.680
- [x] Grube Radio (EDHB) | 132.015
- [x] Büsum Radio (EDXB) | 125.860
- [x] St. Michel Radio (EDXM) | 132.990
- [x] Rendsburg Radio (EDXR) | 123.655
- [x] Neumünster Radio (EDHN) | 136.410
- [x] Itzehoe Radio (EDHF) | 127.110
- [x] Sierksdorf Radio (EDXT) | 125.385
- [x] Wahlstedt Radio (EDHW) | 128.910
- [x] Hartenholm Radio (EDHM) | 118.130
- [x] Norderney Radio (EDWY) | 122.605
- [x] Spieka Radio (EDXN) | 121.030
- [x] Leer Radio (EDWF) | 130.780
- [x] Westerstede Radio (EDWX) | 122.685
- [x] Conneforde Radio (EDWP) | 121.190
- [x] Barssel Radio (EDXL) | 129.135
- [x] Blexen Radio (EDWT) | 120.605
- [x] Kührstedt Radio (EDXZ) | 135.005
- [x] Ahrenlohe Radio (EDHO) | 127.560
- [x] Stade Radio (EDHS) | 132.740
- [x] Seedorf Radio (EDXS) | 119.665
- [x] Karlshöfen Radio (EDWK) | 118.930
- [x] Hüttenbusch Radio (EDXU) | 120.835
- [x] Lauenbrück Radio (EDHU) | 124.485
- [x] Wümme Radio (EDXQ) | 136.015
- [x] Ganderkesee Radio (EDWQ) | 118.630
- [x] Oldenburg Radio (EDWH) | 118.180
- [x] Varrelbusch Radio (EDWU) | 132.565
- [x] Weser-Wümme Radio (EDWM) | 133.705
- [x] Verden Radio (EDWV) | 130.660
- [x] Hoya Radio (EDHY) | 120.710
- [x] Hodenhagen Radio (EDVH) | 119.005
- [x] Nienburg Radio (EDXI) | 133.165
- [x] Damme Radio (EDWC) | 133.305
- [x] Achmer Radio (EDXA) | 123.055
- [x] Osnabrück Radio (EDWO) | 118.680
- [x] Rheine Radio (EDXE) | 126.685
- [x] Bohmte Radio (EDXD) | 118.985
- [x] Melle Radio (EDXG) | 125.835
- [x] Hildesheim Radio (EDVM) | 118.310
- [x] Ithwiesen Radio (EDVT) | 130.655
- [x] Pyrmont Radio (EDVW) | 121.180
- [x] Borkhausen Radio (EDVF) | 121.010
- [x] Hölleberg Radip (EDVL) | 130.080
- [x] Mengeringhausen Radio (EDVG) | 119.735
- [x] Wismar Radio (EDCW) | 125.915
- [x] Rerik Radio (EDCR) | 126.505
- [x] Purkshof Radio (EDCX) | 135.005
- [x] Stralsund Radio (EDBV) | 118.630
- [x] Pinnow Radio (EDBP) | 118.005
- [x] Waren Radio (EDOW) | 130.330
- [x] Schmoldow Radio (EDBY) | 136.015
- [x] Tutow Radio (EDUW) | 132.790
- [x] Neustadt-Glewe Radio (EDAN) | 118.815
- [x] Müriz Radio (EDAX) | 118.990
- [x] Pasewalk Radio (EDCV) | 125.860
- [x] Pritzwalk Radio (EDBU) | 122.685
- [x] Lüchow Radio (EDHC) | 125.365
- [x] Wilsche Radio (EDVQ) | 121.410
- [x] Gardelegen Radio (EDOC) | 133.190
- [x] Peine Radio (EDVP) | 122.830
- [x] Salzgitter Radio (EDVS) | 122.855
- [x] Schäferstuhl Radio (EDVJ) | 132.990
- [x] Gandersheim Radio (EDVA) | 123.005
- [x] Northeim Radio (EDVN) | 118.705
- [x] Eichsfeld Radio (EDHD) | 124.030
- [x] Oschersleben Radio (EDOL) | 129.405
- [x] Schönebeck Radio (EDOZ) | 125.860
- [x] Mühlingen Radio (EDOM) | 136.410
- [x] Zerbst Radio (EDUZ) | 124.485
- [x] Burg Radio (EDBG) | 135.005
- [x] Lüsse Radio (EDOJ) | 128.755
- [x] Oehna Radio (EDBO) | 123.260
- [x] Reinsdorf Radio (EDOD) | 130.655
- [x] Lönnewitz Radio (EDUF) | 132.360
- [x] Finsterwalde Radio (EDAS) | 125.365
- [x] Schacksdorf Radio (EDUS) | 134.540
- [x] Bronkow Radio (EDBQ) | 130.330
- [x] Neuhausen Radio (EDAP) | 122.730
- [x] Eisenhüttenstadt Radio (EDAE) | 134.535
- [x] Kyritz Radio (EDBK) | 122.730
- [x] Klietz Radio (EDCL) | 122.380
- [x] Segeletz Radio (EDAI) | 126.010
- [x] Stölln Radio (EDOR) | 130.080
- [x] Eggersdorf Radio (EDCE) | 123.005
- [x] Neuhardenberg Radio (EDON) | 119.130
- [x] Saarmund Radio (EDCS) | 123.655
- [x] Brandenburg Radio (EDBE) | 118,630
- [x] Fehrbellin Radio (EDBF) | 133.940
- [x] Stechow Radio (EDUA) | 133.585

Military AFIS Towers:
- [x] Diepholz Radio (ETND) | 122.530 (non Military Radio for civil operations, I think)
- [x] Meppen Radio (ETWM) | 122.100 (military AFIS)

Other/Remarks:
EDBD, EDUB, EDCN closed. Still on PHX
EDOG no freq. but on PHX
Some Freq. used twice , maybe limit freq. range or fictional freq. if they are to close? Normal freq. range is 15NM till 3000 feet

**Comment by hannesaltmann** [comment]
In der internen Diskussion ob und wie alle Plätze umgesetzt werden.

**Comment by hannesaltmann** [comment]
> > In der internen Diskussion ob und wie alle Plätze umgesetzt werden.
> 
> Roger, soll ich die anderen fehlenden Plätze noch hinzufügen?

Das wäre super! :)

**Comment by hannesaltmann** [comment]
Die Stationsnamen kannst du aber gern alle Radio nennen. Auch wenn das in der AIP noch nicht einheitlich ist, regelt eine Übergangsregelung des BAF die Verwendung des Radio Rufzeichens, statt des Info Rufzeichens.

**Comment by hannesaltmann** [comment]
> Das sollte alles sein, ich werde die nächsten Tage mal überprüfen ob das alles richtig ist, aber ich glaube ihr werdet das auch mit der AIP vergleichen, oder?
> 
> @hannesaltmann

Super, vielen Dank! Ich werde mich zeitnah darum kümmern zu vergleichen, welche Frequenzen wir bereits auf Vatsim haben und welche es noch nicht ins Sectorfile geschafft haben. Sobald die Frequenzen bei VATEUD eingetragen sind, kümmere ich mich um das Sectorfile :)

**Comment by hannesaltmann** [comment]
Added next AIRAC
