### ISSUE TITLE
Idea: Old Logins EDUU/YY

### ISSUE THREAD

**Issue by pa-ulex** [VATGER-Nav/edww-package#329]
EDUU still has HVL and OSE as old logins. The high sector would still have an odd name or the two first letters and then the H thereafter.
EDYY: HOL also has the old login. CEL, SOL and JEV have the same problem as OSE High with the logins.

**Comment by hannesaltmann** [comment]
This will not be changed as high sectors are rarely staffed thus making it easier to refer to the current lower-upper sector names in general.
