### ISSUE TITLE
Update old GND Layouts

### ISSUE THREAD

**Issue by ManuelPick** [VATGER-Nav/edww-package#340]
- [x] EDAH
- [x] EDDW
- [x] EDXW
- [x] EDVK
- [x] ETHB
- [x] ETHC
- [x] ETHS
- [x] ETND
- [x] ETNL
- [x] ETNS
- [x] ETSH 

Low Priority as everything is up to date. More QoL Update for future changes.

**Comment by hannesaltmann** [comment]
ETNS as last airport now merged
