### ISSUE TITLE
Add Airspace Details to PHX Pack (Alt+A)

### ISSUE THREAD

**Issue by ManuelPick** [VATGER-Nav/edww-package#357]
It was requested to be able to see airspace infos in the PHX pack like in the Radar packs. (Alt+A)

**Comment by hannesaltmann** [comment]
Vielleicht sinnvoll das dann als generelle Map zu machen (ähnlich wie die Topo oder MVA Maps). Dann haben wir nicht die gleiche Map an drei verschiedenen Orten.

**Comment by ManuelPick** [comment]
> Vielleicht sinnvoll das dann als generelle Map zu machen (ähnlich wie die Topo oder MVA Maps). Dann haben wir nicht die gleiche Map an drei verschiedenen Orten.

+1
