### ISSUE TITLE
Squawk plugin is not loading due to exception

### ISSUE THREAD

**Issue by ascarion** [VATGER-Nav/edww-package#379]
The squawks.dll plugin is not loading due to causing an exception on load. 

![EuroScope_voeXrXGJZO](https://github.com/user-attachments/assets/f194d4bf-cc92-4b15-a45f-b9823fe03ac5)

Windows 11, Euroscope 3.2.3.2, EDWW Profile

Addendum: Loading the extension meant for the Phoenix profiles will work fine.

**Comment by hannesaltmann** [comment]
Fixed with the new package version. The dll was outdated.
