### ISSUE TITLE
A388 EDDH Standzuweisung

### ISSUE THREAD

**Issue by GeheimagentNr1** [VATGER-Nav/edww-package#406]
Ich hatte heute einen A388 inbound EDDH.
Das GRP hat beim automatisch zuweisen des Gates aber nur 91-93 vorgeschlagen. Stand 06 als A380 Stand wurde nicht automatisch zugewiesen.

**Comment by hannesaltmann** [comment]
> Ich hatte heute einen A388 inbound EDDH. Das GRP hat beim automatisch zuweisen des Gates aber nur 91-93 vorgeschlagen. Stand 06 als A380 Stand wurde nicht automatisch zugewiesen.

Moin, Position 06 ist ein Gate ausschließlich für Non-Schengen Flüge. Flüge aus Schengen Ländern werden somit nicht auf Stand 06 gestellt. Non-Schengen Flüge werden außerdem korrekt zugewiesen, so lange Position 06A oder Position 06B
