### ISSUE TITLE
EDDV Transitions

### ISSUE THREAD

**Issue by Calaelen** [VATGER-Nav/edww-package#432]
Könnten bitte die open Transitions in EDDV im Assign Arrival Menu mit eingebaut werden?
Auf Grund der Verkehrslage an Events werden wir hier versuchen diese mehr zu clearen.

NIE27, NIE09
CEL27, CEL09
DLE27
ROBE09

Eine Unterscheidung L/R ist nicht notwendig, da diese ja open sind. Da vPilots das sonst mit den published ILS via XXX verschwechseln, bekommen diese explizit das ILS/runway noch hinterher.

![image](https://github.com/user-attachments/assets/79db55af-7fd7-4b51-85a2-1d565af652d2)

**Comment by hannesaltmann** [comment]
Beim nächsten Release des Sectorfiles behoben
