### ISSUE TITLE
[PHX, EDWW] 777 Stand assignment EDDB

### ISSUE THREAD

**Issue by lucianoasmus** [VATGER-Nav/edww-package#437]
777 Freighter kriegt in EDDB die northern cargo stnads (19-27), vielleicht stattdessen auf Deltas, da nicht zugelassen für N1 abeam stands (up to Code D, 777 ist aber E)

**Comment by hannesaltmann** [comment]
Also die Stands sind alle mit max. wingspan 51.99 m definiert. Ich habe das jetzt nochmal verändert, aber eigentlich sollte die B777 auf stand 52 oder dem D-Apron parken.
