### ISSUE TITLE
Emergencies (7700) nicht 100% rot

### ISSUE THREAD

**Issue by lucianoasmus** [VATGER-Nav/edww-package#44]
Gibt es die Möglichkeit, dass auch TopSky Items im Tag bei emergencies (sq 7700) rot eingefärbt werden? Ob non-concerned, concerened oder assumed... Mich interessiert es durchaus auch als Nachbarsektor, ob der Kollege gerade mit einem Flugzeug in Luftnotlage zu arbeiten hat (erhöhter workload). 
Da ist ein bisschen mehr Party auf dem Radar hilfreich :D

Ich hatte letztens einen auf unicom, der 7700 drin hatte, der war non-concerned und es waren nur Default-ES items rot, rest war dunkelblau eingefärbt.

**Comment by hannesaltmann** [comment]
Wenn, dann ist das ein Topsky Bug. Im Pack sind die Farben korrekt eingestellt. Ich habe mal einen Bugreport im VATSCA Forum geschrieben.
