### ISSUE TITLE
Military CTRs

### ISSUE THREAD

**Issue by pascalgrotzke** [VATGER-Nav/edww-package#45]
CTRs as ETHC or ETHB are permanently displayed. 
I would prefer to activate it manually and implement an auto display if the station comes online.

**Comment by hannesaltmann** [comment]
APP/CTR covers ETHC and ETHB due to the top-down principle. Therefore I would not disable controlled airspace. But I will leave this issue open for discussion.

**Comment by Calaelen** [comment]
Military D-HX CTRs, die auf Vatsim zu 99.99% nicht aktiv sind.
Top-Down Service beschränkt sich auf "on own discretion" Anweisungen.

Wenn dann (mit GCAP) wirklich mal ein Tier 2 military endorsment Tower online kommt, ist die CTR immer noch inaktiv ohne Traffic. Aber dann macht das einblenden mit der aktiven Farbe zumindest Sinn.

**Comment by hannesaltmann** [comment]
Okay GCAP Tier 2 spricht dann echt für das Aktivieren, wenn TWR da ist.

**Comment by FlorianUelzen** [comment]
Ich finde die können ruhig weiterhin (grau oder wie auch immer da bleiben) um einfach eine visuelle Referenz zu haben wenn sich dort n target bewegt zB VFR da nehme ich oft die CTRs und airspace boundaries als Anhaltspunkt um genau zu wissen wo er ist. Wenn besetzt grün bzw türkis oder wie auch immer befürworte ich .... Ich finde man sollte alle CTRs oder aber auch RMZ! grün hinterlegen wenn diese besetzt sind (meinetwegen auch außer: DW, DH, DV, DB)
