### ISSUE TITLE
EDDH23 STAR fixes missing

### ISSUE THREAD

**Issue by pascalgrotzke** [VATGER-Nav/edww-package#53]
MAP:EDDH 23 FIX
FOLDER:FIXES
COLOR:Active_Map_Type_2
ACTIVE:RWY:ARR:EDDH23:DEP:*
AND_ACTIVE:ID:ALR,HEI,WC:*:*:HAME,HAMW
ACTIVE:RWY:ARR:EDDH23:DEP:*
AND_ACTIVE:ID:HAME,HAMW,DHAT:*:*:*
ZOOM:10
TEXT:DH600:00
TEXT:DH609:09
TEXT:DH610:10
TEXT:DH611:11
TEXT:DH612:12
TEXT:DH614:14
TEXT:DH615:15
TEXT:DH620:20
TEXT:DH632:32
TEXT:DH633:33
TEXT:DH634:34
TEXT:DH635:35
TEXT:DH655:55
TEXT:DH656:56
TEXT:DH657:57
TEXT:PISAS:PISAS
SYMBOL:FIX ENR:RARUP
SYMBOL:FIX ENR:BOGMU
SYMBOL:FIX ENR:NOLGO
SYMBOL:FIX ENR:RIBSO

**Comment by hannesaltmann** [comment]
Was fixed with v0.9.6

**Comment by ascarion** [comment]
While the labels are now present, the actual point indicator (+ or x etc) is not shown. 

![1yf](https://github.com/VATGER-Nav/edww-package/assets/237600/846d7037-31b5-44c3-bf13-afe005b5de38)
