### ISSUE TITLE
EDDH33 STAR fixes missing

### ISSUE THREAD

**Issue by pascalgrotzke** [VATGER-Nav/edww-package#54]
MAP:EDDH 33 FIX
FOLDER:FIXES
COLOR:Active_Map_Type_2
ACTIVE:RWY:ARR:EDDH33:DEP:*
AND_ACTIVE:ID:ALR,HEI,WC:*:*:HAME,HAMW
ACTIVE:RWY:ARR:EDDH33:DEP:*
AND_ACTIVE:ID:HAME,HAMW,DHAT:*:*:*
ZOOM:10
TEXT:DH804:04
TEXT:DH805:05
TEXT:DH806:06
TEXT:DH807:07
TEXT:DH808:08
TEXT:DH809:09
TEXT:DH810:10
TEXT:DH811:11
TEXT:DH812:12
TEXT:DH813:13
TEXT:DH814:14
TEXT:DH815:15
TEXT:DH829:29
TEXT:DH830:30
TEXT:DH831:31
TEXT:DH832:32
TEXT:DH833:33
TEXT:DH834:34
TEXT:DH835:35
TEXT:DH854:54
TEXT:DH855:55
TEXT:DH856:56
TEXT:DH857:57
TEXT:DH858:58
TEXT:SOSAX:SOSAX
SYMBOL:FIX ENR:RARUP
SYMBOL:FIX ENR:BOGMU
SYMBOL:FIX ENR:NOLGO
SYMBOL:FIX ENR:RIBSO

**Comment by hannesaltmann** [comment]
Was fixed with v0.9.6
