### ISSUE TITLE
Leaderlines in minutes

### ISSUE THREAD

**Issue by pascalgrotzke** [VATGER-Nav/edww-package#55]
![grafik](https://github.com/VATGER-Nav/edww-package/assets/76235605/5f2c2287-b146-4e01-ae30-fc85a84ed362)
Can we change that to minutes instead of nm?

**Comment by hannesaltmann** [comment]
Leaderlines will be controlled through the Track Control Menu located in the radar menu. The Euroscope leaderlines will usually not be used. 

Menu can be found here:
![image](https://github.com/VATGER-Nav/edww-package/assets/71515220/373dcada-6bd0-42bc-84f7-ecac0eeb9af1)

**Comment by pascalgrotzke** [comment]
I know, but I (and some other people) use them

**Comment by Calaelen** [comment]
"The Euroscope leaderlines will usually not be used."

We train radar controllers to use them and "usually" is not "everyone". Default can be invisible but please turn it into minutes by default.
