### ISSUE TITLE
EDDV CTR not visible if Tower is online

### ISSUE THREAD

**Issue by Calaelen** [VATGER-Nav/edww-package#56]
I am online as EDDV_APP, not EDDV CTR?  EDDV_TWR is online

![image](https://github.com/VATGER-Nav/edww-package/assets/524760/ae86d5c0-a2d9-4d7e-a1a8-098833459fdc)

**Comment by hannesaltmann** [comment]
Konnte ich in verschiedenen Konstellationen nicht reproduzieren. Besteht das Problem auch, wenn du Euroscope nochmal neu startest?

**Comment by hannesaltmann** [comment]
@Calaelen ?

**Comment by Calaelen** [comment]
Bisher nicht wieder gelotst auf Approach mit Tower, um das nochmal zu prüfen. Bitte Ticket noch bisschen offen lassen, melde mich.

**Comment by hannesaltmann** [comment]
Danke!
