### ISSUE TITLE
Missing AMAN Config for EDDH

### ISSUE THREAD

**Issue by FriMax67** [VATGER-Nav/edww-package#59]
Just missing an AMAN Profile for EDDH. Pull REQ will follow.

**Comment by pascalgrotzke** [comment]
The system is not being used in Hamburg.

**Comment by hannesaltmann** [comment]
> The system is not being used in Hamburg.

But can't we add it as an enhancement? Just because it is available it doesn't mean it shall be used by everyone. Or am I missing anything crucial?

**Comment by pascalgrotzke** [comment]
As long as it doesn't show up on startup everytime.. :D

**Comment by hannesaltmann** [comment]
The automatic start-up was already disabled two updates ago.
