### ISSUE TITLE
CTL Flag gets activated out of nowhere for ALL controllers

### ISSUE THREAD

**Issue by Calaelen** [VATGER-Nav/edww-package#69]
![image](https://github.com/VATGER-Nav/edww-package/assets/524760/88e2feb4-6a7f-4525-994c-c470892fc39e)

Noone set this Flag and usually it is a local flag the other controllers can't see.
Tonight we had 3 situations, where it set itself on CTL for HAME and Director.

**Comment by hannesaltmann** [comment]
You may have clicked it accidentally when the aircraft was far from the airport. In this case, you won't notice until the predicted route is less than 20 NM away from the airport. 

This is not a bug and can happen from time to time. What I can do is increase the range where the CTL will be displayed to instantly show the misclick. Still, so won't stop you from accidentally clicking it.

**Comment by hannesaltmann** [comment]
I will try to set the CTL flag to a right-click on the AFL. This might reduce the chance of misclicks
