### ISSUE TITLE
mismatching MVA Map + EDVE MVA

### ISSUE THREAD

**Issue by Calaelen** [VATGER-Nav/edww-package#70]
new beta Pack:
![image](https://github.com/VATGER-Nav/edww-package/assets/524760/0695984b-16b8-4e59-9057-405a772b7e06)

old Pack:
![image](https://github.com/VATGER-Nav/edww-package/assets/524760/36a3b40a-435e-40c1-8073-6e81e2a30340)

Which area is correct now? Just as a check.

Also:  EDVE MVA is still outdated. New lower MVA south-east for ILS26 vectorings.

**Comment by hannesaltmann** [comment]
The correct one is from DFS AIP ENR 6: https://aip.dfs.de/BasicIFR/pages/C000B7.html

I noticed some mismatching in the area of EDVK, EDOP and EDAH. Will update it soon!

**Comment by Calaelen** [comment]
So the new pack is the correct one?  (I was asked which one is valid)

**Comment by hannesaltmann** [comment]
> So the new pack is the correct one? (I was asked which one is valid)

Neither is completely correct. But for the EDDV/EDVE/EDVK area is second picture is correct.

**Comment by hannesaltmann** [comment]
Will be fixed with the next update.
