### ISSUE TITLE
Custom color für Map Type 1

### ISSUE THREAD

**Issue by HanJencke** [VATGER-Nav/edww-package#87]
Das Türkis für die Airspaces in Hannover finde ich wirklich sehr störend. Insb. bei Top-Down. Wäre es eine Möglichkeit die Zeile Color_Active_Map_Type_1=110,90,80 ebenfalls wie die für Type 2 in die Local Settings mitaufzunehmen?

**Comment by hannesaltmann** [comment]
Mit der custom color 1 wären auch die Farben der ED-Rs/TRAs und ein paar anderen Dingen abgeändert. Das möchte dann vielleicht nicht sofort jeder. Ich würde die default Farbe von EDDV auf einen anderen Farbslot legen, sodass man dann nur diese Map ändert und nicht die gleich alles. 

Aber gute Idee auf jeden Fall!
