### ISSUE TITLE
Shortcut enroute Fixes

### ISSUE THREAD

**Issue by BremenIdentified** [VATGER-Nav/edww-package#89]
Moin,
der über "ALT+N" gesteuerte Filter der enroute-fixes scheint nicht zu funktionieren. Dieser bleibt, sowohl beim CTR als auch beim TWR-Profil deaktiviert.

**Comment by hannesaltmann** [comment]
Danke, wird sich angeschaut. Beim TWR Profile ist aber auf jeden Fall dieser Shortcut nicht verfügbar.

**Comment by BremenIdentified** [comment]
Moin Hannes,
ich habe mich grade mit V0.9.9 als OBS eingeloggt, nachdem ich das ganze Paket komplett neu installiert habe.
Es schient so, als würden im CTR-Profil noch immer folgende Commands nicht funktionieren:

- ALT-N - enroute fixes - hier werden weder die Fixes, noch die dazugehörigen Label eingeblendet; es passiert nichts.

zudem war immer hilfreich:
- ALT-Y - Sector upper  - (jetzt passiert nichts)
- ALT-C - Sector lower - (jetzt rückt die Maus in Screen-Center)

Danke dir für deine Arbeit!

**Comment by hannesaltmann** [comment]
Hi,

ALT+N muss ich nochmal schauen. Labels werden aber nicht kommen, das ist in der Map welche durch den Shortcut aktiviert wird gar nicht vorgesehen. 

ALT+Y gibt es nicht in Pack und ist auch nicht vorgesehen
ALT+C hast du recht. Das muss angepasst werden.
