### ISSUE TITLE
RG Bremen Plugin outdated SIDSTAR file

### ISSUE THREAD

**Issue by a-bern** [VATGER-Nav/edww-package#98]
Hi,

I noticed the following SIDSTAR File is configured in the "RG Bremen.cfg" file: https://dms.vatsim-germany.org/s/WYYRBRFQcHF3YFw/download/clbdesc_sidstar.txt

It looks like this file has some outdates SIDS. For example EDXW: 
EDXW SID OLDIP 1A
EDXW SID OLDIP 1N

Should be 1A and 1B. The old pack has the following url configured: https://dms.vatsim-germany.org/s/CQxss89irorjZmp/download/clbdesc_sidstar.txt - This file lists the expected SIDs for EDXW

Thanks
Alex

**Comment by hannesaltmann** [comment]
Now fixed, regardless of beta pack version
